(TeX-add-style-hook
 "Skript-ST1"
 (lambda ()
   (LaTeX-add-bibitems
    "Klenke2012"
    "R-Core-Team2015")
   (LaTeX-add-environments
    '("Liste" LaTeX-env-args ["argument"] 0)
    '("resListeN" LaTeX-env-args ["argument"] 0)
    '("drListeM" LaTeX-env-args ["argument"] 0)
    '("drListeT" LaTeX-env-args ["argument"] 0)
    '("drListeB" LaTeX-env-args ["argument"] 0)
    '("drListeS" LaTeX-env-args ["argument"] 0)
    '("dgListeM" LaTeX-env-args ["argument"] 0)
    '("dgListeT" LaTeX-env-args ["argument"] 0)
    '("dgListeB" LaTeX-env-args ["argument"] 0)
    '("dgListeS" LaTeX-env-args ["argument"] 0)
    '("dbListeM" LaTeX-env-args ["argument"] 0)
    '("dbListeT" LaTeX-env-args ["argument"] 0)
    '("dbListeB" LaTeX-env-args ["argument"] 0)
    '("dbListeS" LaTeX-env-args ["argument"] 0)
    '("dbraunListeM" LaTeX-env-args ["argument"] 0)
    '("dbraunListeT" LaTeX-env-args ["argument"] 0)
    '("dbraunListeB" LaTeX-env-args ["argument"] 0)
    '("dbraunListeS" LaTeX-env-args ["argument"] 0)
    '("dgrauListeM" LaTeX-env-args ["argument"] 0)
    '("dgrauListeT" LaTeX-env-args ["argument"] 0)
    '("dgrauListeB" LaTeX-env-args ["argument"] 0)
    '("dgrauListeS" LaTeX-env-args ["argument"] 0)
    '("dsListeM" LaTeX-env-args ["argument"] 0)
    '("dsListeT" LaTeX-env-args ["argument"] 0)
    '("dsListeB" LaTeX-env-args ["argument"] 0)
    '("dsListeS" LaTeX-env-args ["argument"] 0)
    '("bewListeM" LaTeX-env-args ["argument"] 0)
    '("bewListeT" LaTeX-env-args ["argument"] 0)
    '("bewListeB" LaTeX-env-args ["argument"] 0)
    '("bewListeS" LaTeX-env-args ["argument"] 0)
    '("sprListeM" LaTeX-env-args ["argument"] 0)
    '("sprListeT" LaTeX-env-args ["argument"] 0)
    '("sprListeB" LaTeX-env-args ["argument"] 0)
    '("sprListeS" LaTeX-env-args ["argument"] 0)
    '("schListeM" LaTeX-env-args ["argument"] 0)
    '("schListeT" LaTeX-env-args ["argument"] 0)
    '("schListeB" LaTeX-env-args ["argument"] 0)
    '("schListeS" LaTeX-env-args ["argument"] 0)
    '("bspListeM" LaTeX-env-args ["argument"] 0)
    '("bspListeT" LaTeX-env-args ["argument"] 0)
    '("bspListeB" LaTeX-env-args ["argument"] 0)
    '("bspListeS" LaTeX-env-args ["argument"] 0)
    '("resListeM" LaTeX-env-args ["argument"] 0)
    '("resListeT" LaTeX-env-args ["argument"] 0)
    '("resListeB" LaTeX-env-args ["argument"] 0)
    '("resListeS" LaTeX-env-args ["argument"] 0)
    '("anmListeM" LaTeX-env-args ["argument"] 0)
    '("anmListeT" LaTeX-env-args ["argument"] 0)
    '("anmListeB" LaTeX-env-args ["argument"] 0)
    '("anmListeS" LaTeX-env-args ["argument"] 0)
    '("bemListeM" LaTeX-env-args ["argument"] 0)
    '("bemListeT" LaTeX-env-args ["argument"] 0)
    '("bemListeB" LaTeX-env-args ["argument"] 0)
    '("bemListeS" LaTeX-env-args ["argument"] 0)
    '("deListeM" LaTeX-env-args ["argument"] 0)
    '("deListeT" LaTeX-env-args ["argument"] 0)
    '("deListeB" LaTeX-env-args ["argument"] 0)
    '("deListeS" LaTeX-env-args ["argument"] 0)
    '("schListeN" LaTeX-env-args ["argument"] 0)
    '("algListeN" LaTeX-env-args ["argument"] 0)
    '("anmListeN" LaTeX-env-args ["argument"] 0)
    '("bemListeN" LaTeX-env-args ["argument"] 0)
    '("bspListeN" LaTeX-env-args ["argument"] 0)
    '("bewListeN" LaTeX-env-args ["argument"] 0)
    '("deListeN" LaTeX-env-args ["argument"] 0)
    '("ListeN" LaTeX-env-args ["argument"] 0)
    '("ListeNii" LaTeX-env-args ["argument"] 0)
    '("ListeNi" LaTeX-env-args ["argument"] 0)))
 :bibtex)

